version: 2

updates:
  # Dépendances backend Maven
  - package-ecosystem: "maven"
    directory: "/backend"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "backend"
      - "security"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
      - "ci-cd"