services:
  postgres:
    image: postgres:16
    container_name: vintage_marketplace_db
    restart: always
    environment:
      POSTGRES_DB: vintage_marketplace
      POSTGRES_USER: vintage_user
      POSTGRES_PASSWORD: vintage_password
    ports:
      - "5432:5432"
    volumes:
      - vintage_marketplace_data:/var/lib/postgresql/data

volumes:
  vintage_marketplace_data: