-- Schema initial, extrait du schema genere par Hibernate (ddl-auto: update)
-- au moment du passage a Flyway. Reflete exactement les entites JPA
-- existantes (User, Item, Order) ; noms de contraintes renommes de facon
-- lisible (Hibernate genere des noms hash illisibles).

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(2000) NOT NULL,
    price NUMERIC(38, 2) NOT NULL,
    image_url VARCHAR(255),
    status VARCHAR(255) NOT NULL,
    seller_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6),
    CONSTRAINT ck_items_status CHECK (status IN ('AVAILABLE', 'SOLD')),
    CONSTRAINT fk_items_seller FOREIGN KEY (seller_id) REFERENCES users (id)
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL,
    buyer_id BIGINT NOT NULL,
    seller_id BIGINT NOT NULL,
    item_price NUMERIC(38, 2) NOT NULL,
    platform_fee NUMERIC(38, 2) NOT NULL,
    seller_amount NUMERIC(38, 2) NOT NULL,
    total_amount NUMERIC(38, 2) NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uq_orders_item_id UNIQUE (item_id),
    CONSTRAINT ck_orders_status CHECK (status IN ('COMPLETED', 'CANCELLED')),
    CONSTRAINT fk_orders_item FOREIGN KEY (item_id) REFERENCES items (id),
    CONSTRAINT fk_orders_buyer FOREIGN KEY (buyer_id) REFERENCES users (id),
    CONSTRAINT fk_orders_seller FOREIGN KEY (seller_id) REFERENCES users (id)
);
