spring:
  application:
    name: vintage-marketplace

  datasource:
    url: jdbc:postgresql://localhost:5433/vintage_marketplace
    username: vintage_user
    password: vintage_password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

app:
  jwt:
    secret: "ZmFrZVNlY3JldEtleUZvclNjaG9vbFByb2plY3RNdXN0QmVMb25nRW5vdWdoMzI="
    expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always

  info:
    env:
      enabled: true

info:
  app:
    name: Collector Backend
    description: Backend Spring Boot pour la marketplace Collector
    version: 1.0.0