name: Backend Security Scan

on:
  workflow_dispatch:

  schedule:
    - cron: '0 6 * * 1'

permissions:
  security-events: write
  contents: read
  actions: read

jobs:
  backend-dependency-check:
    uses: ./.github/workflows/sca-dependency-scan.yml
    secrets: inherit
