name: main-pipeline

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'docker-compose.yml'
      - '.github/workflows/**'

  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'docker-compose.yml'
      - '.github/workflows/**'

  workflow_dispatch:

  schedule:
    - cron: '0 2 * * 1'

permissions:
  security-events: write
  contents: read
  actions: read

jobs:
  backend-tests:
    uses: ./.github/workflows/backend-tests.yml

  frontend-build:
    uses: ./.github/workflows/frontend-build.yml

  code-quality-sast:
    uses: ./.github/workflows/code-quality-sast.yml
    secrets: inherit

  sca-dependency-scan:
    uses: ./.github/workflows/sca-dependency-scan.yml
    secrets: inherit

  secret-scanning:
    uses: ./.github/workflows/secret-scanning.yml

  secure-iac-dockerfile-scan:
    uses: ./.github/workflows/iac-dockerfile-scan.yml

  docker-build:
    needs:
      - backend-tests
      - frontend-build
    uses: ./.github/workflows/docker-build.yml
